### ISSUE TITLE
Question about score normalization

### ISSUE THREAD

**Issue by evcu** [alecwangcq/GraSP#2]
Hi Chaoqi,

I was wondering whether dividing by gradient norm is necessary. It seems like it doesn't affect the ordering and therefore the results. I might be missing something.

https://github.com/alecwangcq/GraSP/blob/f17d87ac537bfce476ac2424171a8b6eb56499db/pruner/GraSP.py#L146

**Comment by alecwangcq** [comment]
You are right. The normalization here is not necessary. Sorry for any confusions.
