### ISSUE TITLE
Question: Why is are the inputs/targets split into different batches?

### ISSUE THREAD

**Issue by samuelstanton** [alecwangcq/GraSP#4]
Hi, quick question. Why are the inputs and targets split into different batches here?

https://github.com/alecwangcq/GraSP/blob/master/pruner/GraSP.py#L82

Did you not have the memory to compute the gradients in a single batch?

**Comment by alecwangcq** [comment]
Hi, sorry for the late reply. 

I had memory overflow issue when I compute the gradients in a single batch for tiny-imagnet. So I split the batch into two. 

If you have any further questions, feel free to reopen this issue. Thanks!
